/** @type {import("@commitlint/types").UserConfig} */
const configuration = {
    extends: ["@commitlint/config-conventional"],
    rules: {
        "body-max-line-length": [2, "always", 100],
        "footer-max-line-length": [2, "always", 100],
        "header-max-length": [2, "always", 100],
        "type-enum": [
            2,
            "always",
            [
                "access",
                "adhesive-bandage",
                "agents",
                "analytics",
                "android",
                "animation",
                "arch",
                "assets",
                "beer",
                "breaking",
                "bricks",
                "build",
                "camera-flash",
                "chore",
                "ci",
                "clown-face",
                "coffin",
                "compat",
                "config",
                "contrib-add",
                "db",
                "dep-add",
                "dep-rm",
                "dep-up",
                "deploy",
                "design",
                "docker",
                "docs",
                "docs-code",
                "downgrade",
                "egg",
                "experiment",
                "feat",
                "feature",
                "fix",
                "fix-ci",
                "flags",
                "i18n",
                "init",
                "ios",
                "iphone",
                "k8s",
                "license",
                "lint",
                "linux",
                "log-add",
                "log-rm",
                "merge",
                "monocle-face",
                "mv",
                "necktie",
                "osx",
                "passport-control",
                "perf",
                "poo",
                "prune",
                "pushpin",
                "quickfix",
                "refactor",
                "refactoring",
                "release",
                "revert",
                "review",
                "security",
                "seed",
                "see-no-evil",
                "seo",
                "skills",
                "specs",
                "stethoscope",
                "style",
                "technologist",
                "test",
                "test-tube",
                "texts",
                "transcend",
                "typo",
                "types",
                "ui",
                "upgrade",
                "ux",
                "wastebasket",
                "windows",
                "wip",
            ],
        ],
    },
};

export default configuration;
