allowBuilds:
  '@danmarshall/deckgl-typings': true
  '@heroui/shared-utils': true
  '@parcel/watcher': true
  '@pulumi/kubernetes': set this to true or false
  '@scarf/scarf': true
  '@swc/core': true
  browser-tabs-lock: true
  core-js: true
  cpu-features: true
  cypress: true
  esbuild: true
  fsevents: set this to true or false
  maplibre-gl: true
  msw: true
  nx: true
  pre-commit: true
  protobufjs: true
  secp256k1: true
  ssh2: true
  unrs-resolver: true

requiredScripts:
  - build

packages:
  - apps/*
  - packages/*

minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.10.8'
  - '@turbo/darwin-arm64@2.10.8'
  - '@turbo/linux-64@2.10.8'
  - '@turbo/linux-arm64@2.10.8'
  - '@turbo/windows-64@2.10.8'
  - '@turbo/windows-arm64@2.10.8'
  - '@types/react-dom@19.2.4'
  - '@types/react@19.2.18'
  - turbo@2.10.8
